Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2022-09, with the labels that each got.

#33 Probe: Gets the last commit date of the repository
  pom.xml
  src/main/java/io/jenkins/pluginhealth/scoring/http/ProbesController.java
  src/main/java/io/jenkins/pluginhealth/scoring/model/Plugin.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/LastCommitDateProbe.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/Probe.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbe.java
  src/main/java/io/jenkins/pluginhealth/scoring/schedule/UpdateCenterScheduler.java
  src/main/java/io/jenkins/pluginhealth/scoring/service/PluginService.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/LastCommitDateProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
Labels: enhancement

#35 Updates Spring-Boot to 2.7.3 and Hibernate Types to 2.18.0
  pom.xml
Labels: dependencies

#32 Creates a context across probe executions for a plugin
  src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
Labels: enhancement

#37 Fixes condition to run probe
  src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
Labels: bug

#36 Application deployment
  .editorconfig
  Jenkinsfile
  compose.yml
  pom.xml
Labels: enhancement
