Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2023-03, with the labels that each got.

#198 Get plugin code coverage record
  src/main/java/io/jenkins/pluginhealth/scoring/model/updatecenter/Plugin.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbe.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/DeprecatedPluginProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/InstallationStatProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/JenkinsCoreProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/UpForAdoptionProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbeTest.java
Labels: enhancement, probe

#211 Adds probe to detect existance of contributing guide on plugin repository
  src/main/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbe.java
  src/main/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoring.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoringTest.java
Labels: enhancement, probe

#209 Setting Gitpod Development Environment
  .gitpod.yml
Labels: chore

#235 Add Documentation for Gitpod
  docs/CONTRIBUTING.adoc
Labels: documentation

#230 Document probe and scoring methods
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/Probe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/Scoring.java
Labels: documentation

#236 Probe to check if Spotbugs is enabled in a plugin
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/SpotBugsProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/SpotBugsProbeTest.java
Labels: enhancement

#245 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/new-probe.yaml
Labels: documentation

#251 Makes sure to use the same version of GitHub API in modules
  core/pom.xml
  pom.xml
  war/pom.xml
Labels: bug

#253 Fixes NPE in SpotBugsProbe when plugin is not part of UpdateCenter
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/SpotBugsProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/SpotBugsProbeTest.java
Labels: bug

#261 Fix last commit date probe execution requirement
  core/src/main/java/io/jenkins/pluginhealth/scoring/model/Plugin.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/LastCommitDateProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/model/PluginTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/model/ProbeResultTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/LastCommitDateProbeTest.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
Labels: bug

#263 Fixes probe requirements to be executed
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContinuousDeliveryProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DependabotProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DependabotPullRequestProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DeprecatedPluginProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DocumentationMigrationProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/InstallationStatProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/JenkinsCoreProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/JenkinsfileProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/LastCommitDateProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/Probe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/PullRequestProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/SpotBugsProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/UpForAdoptionProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/AbstractProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/ContinuousDeliveryProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DependabotProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DependabotPullRequestProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DeprecatedPluginProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DocumentationMigrationProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/InstallationStatProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/JenkinsCoreProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/JenkinsfileProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/LastCommitDateProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/PullRequestProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/SpotBugsProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/UpForAdoptionProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbeTest.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
Labels: bug

#266 Removes contributing guide from repository scoring
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoringTest.java
Labels: enhancement
