Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2023-04, with the labels that each got.

#278 `jenkins-version` probe requires update-center data
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/JenkinsCoreProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/JenkinsCoreProbeTest.java
Labels: bug

#279 `scm` probe only executed when the plugin is in update center
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbeTest.java
Labels: bug

#280 CI using artifact caching proxy
  Jenkinsfile
Labels: chore

#274 Creates score statistics API
  core/src/main/java/io/jenkins/pluginhealth/scoring/repository/PluginRepository.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/repository/ScoreRepository.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/service/ScoreService.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/service/ScoreServiceIT.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/service/ScoreServiceTest.java
Labels: enhancement

#289 Update code coverage step
  Jenkinsfile
Labels: chore

#294 Adds test to validate recordCoverage check title
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbeTest.java
Labels: bug

#284 Delete old scores automatically from plugin
  core/src/main/java/io/jenkins/pluginhealth/scoring/repository/ScoreRepository.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/service/ScoreService.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/repository/ScoreRepositoryIT.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/schedule/DeleteOldScoreScheduler.java
Labels: enhancement

#295 Improves code coverage of the project
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/JenkinsCoreProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/PullRequestProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/JenkinsCoreProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/PullRequestProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/service/PluginServiceIT.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/service/ScoreServiceIT.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/service/PluginDocumentationService.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/http/ScoreAPITest.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/schedule/UpdateCenterSchedulerIT.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/service/PluginDocumentationServiceTest.java
Labels: chore

#286 Improves plugin score report api
  core/src/main/java/io/jenkins/pluginhealth/scoring/service/ScoreService.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/service/ScoreServiceIT.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/http/ScoreAPI.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/http/ScoreAPITest.java
Labels: enhancement
