Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2023-01, with the labels that each got.

#176 Fix score transactional save
  src/main/java/io/jenkins/pluginhealth/scoring/service/ScoreService.java
Labels: bug

#177 Protects `/api/scores` against plugins with null version
  src/main/java/io/jenkins/pluginhealth/scoring/config/VersionNumberType.java
  src/main/java/io/jenkins/pluginhealth/scoring/model/Plugin.java
  src/main/java/io/jenkins/pluginhealth/scoring/service/ProbeService.java
  src/main/java/io/jenkins/pluginhealth/scoring/service/ScoreService.java
Labels: bug

#179 Count open-pull request on a plugin repository
  src/main/java/io/jenkins/pluginhealth/scoring/config/GitHubHealthIndicator.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeContext.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/PullRequestProbe.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbe.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/InstallationStatProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/PullRequestProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbeTest.java
Labels: enhancement, probe

#182 Plugins can be deprecated on their own
  src/main/java/io/jenkins/pluginhealth/scoring/probes/DeprecatedPluginProbe.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/DeprecatedPluginProbeTest.java
Labels: bug

#183 Ignore raw result of pull request count
  src/main/java/io/jenkins/pluginhealth/scoring/service/ProbeService.java
Labels: bug

#185 Plugin deprecation does not imply security issue
  src/main/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbe.java
  src/main/java/io/jenkins/pluginhealth/scoring/probes/UpForAdoptionProbe.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbeTest.java
Labels: bug

#190 Fixes incorrect contribution guideline
  .env.example
  CONTRIBUTING.adoc
Labels: documentation

#191 Improve error management when persisting entities
  src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  src/main/java/io/jenkins/pluginhealth/scoring/scores/ScoreEngine.java
  src/test/java/io/jenkins/pluginhealth/scoring/service/ScoreServiceIT.java
Labels: bug

#200 Instructions to connect to the database
  CONTRIBUTING.adoc
Labels: documentation
