Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2023-10, with the labels that each got.

#372 feat: provide an ARM64 version of the image
  Jenkinsfile
Labels: enhancement

#382 Reverting bump jjwt from 0.11.5 to 0.12.2
  pom.xml
Labels: bug

#379 Fixes accessing to method on invalid object
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/SpotBugsProbe.java
Labels: bug

#381 Prevents executing probes on plugin with no scm configured
  war/src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
Labels: bug

#385 Fixing probe version since changed in #379
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/SpotBugsProbe.java
Labels: skip-changelog

#383 Protects documentation service against potential null pointer exception
  war/src/main/java/io/jenkins/pluginhealth/scoring/service/PluginDocumentationService.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/service/PluginDocumentationServiceTest.java
  war/src/test/resources/documentation-urls/plugin-documentation-urls-with-nulls.json
Labels: bug

#386 Makes sure external downloads happen only once
  war/src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
Labels: enhancement
