Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2023-02, with the labels that each got.

#201 Uses OkHttp to cache responses from GitHub
  pom.xml
  src/main/java/io/jenkins/pluginhealth/scoring/config/GithubConfiguration.java
Labels: enhancement, dependencies

#203 Improves contribution guidance
  .env.example
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/new-probe.yaml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  Jenkinsfile
  README.adoc
  docs/.env.example
  docs/ARCHITECTURE.adoc
  docs/CONTRIBUTING.adoc
  src/main/java/io/jenkins/pluginhealth/scoring/probes/PullRequestProbe.java
Labels: documentation, chore

#205 Detecting when a plugin is not published in the Update Center anymore
  src/main/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbe.java
  src/main/java/io/jenkins/pluginhealth/scoring/scores/UpdateCenterPublishedPluginDetectionScoring.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbeTest.java
  src/test/java/io/jenkins/pluginhealth/scoring/scores/UpdateCenterPublishedPluginDetectionScoringTest.java
Labels: enhancement, probe

#212 Fixes update-center probe phrasing
  src/main/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbe.java
  src/test/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbeTest.java
Labels: skip-changelog

#213 Reconfigure how new code issues are compared
  Jenkinsfile
  pom.xml
  src/analytics/checkstyle-configuration.xml
  src/analytics/spotbugs-exclude.xml
  src/main/java/io/jenkins/pluginhealth/scoring/config/VersionNumberType.java
Labels: chore, skip-changelog

#215 Fix misleading name for the Update Center publication scoring implementation
  src/main/java/io/jenkins/pluginhealth/scoring/scores/UpdateCenterPublishedPluginDetectionScoring.java
  src/test/java/io/jenkins/pluginhealth/scoring/scores/UpdateCenterPublishedPluginDetectionScoringTest.java
Labels: internal

#220 chore: pin GitHub actions with their SHA-1 instead of their version number
  .github/workflows/release-drafter.yml
Labels: chore
