Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2024-01, with the labels that each got.

#418 Fixed all broken links of ARCHITECTURE.adoc and a faulty file name
  docs/ARCHITECTURE.adoc
Labels: documentation

#434 Update build configuration
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  core/pom.xml
  mvnw
  mvnw.cmd
  pom.xml
  test/pom.xml
  war/pom.xml
  war/yarn.lock
Labels: chore

#437 Fixes adoption and dependabot / renovate typo
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/AbstractDependencyBotConfigurationProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/AdoptionScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DependabotProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/RenovateProbeTest.java
Labels: bug

#443 Better detect dependency bot configuration file in plugin repository
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/AbstractDependencyBotConfigurationProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DependabotProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/RenovateProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/AdoptionScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DependabotProbeTest.java
Labels: enhancement
