Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2024-10, with the labels that each got.

#530 Limit scoring issues contamination
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeCoverageProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DependabotPullRequestProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/PluginDescriptionMigrationProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/Probe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/Scoring.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/SecurityWarningScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/PluginDescriptionMigrationProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbeTest.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngine.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeEngineTest.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/scores/ScoringEngineTest.java
Labels: bug

#554 Plugin repository ownership based on repository name
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeOwnershipProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/CodeOwnershipProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/SCMLinkValidationProbeTest.java
Labels: enhancement

#555 Project configuration does not need developers listing
  pom.xml
Labels: chore, skip-changelog

#556 chore(Jenkinsfile) avoid rebuilding tags and PRs daily
  Jenkinsfile
Labels: chore, skip-changelog

#558 Codeowner using bad repository name
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeOwnershipProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ProbeContext.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/CodeOwnershipProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/ProbeContextTest.java
Labels: bug
