Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2024-04, with the labels that each got.

#501 Improving webview of plugin scores
  war/package.json
  war/src/main/js/index.js
  war/src/main/less/modules/score.less
  war/src/main/resources/templates/scores/details.html
  war/yarn.lock
Labels: enhancement

#502 Removes unnecessary scripts from repository
  .gitignore
  Jenkinsfile_report
  fetch-report.sh
Labels: internal

#507 Empty reasons for code ownership scoring
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/CodeOwnershipProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/CodeOwnershipProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoringTest.java
Labels: bug

#508 Adds resolution to setup JEP-229
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoring.java
Labels: patch

#509 Fixes missing version increment for contributing guide probe
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbe.java
Labels: bug

#446 Adds link to security advisory to security probe and scoring display
  core/src/main/java/io/jenkins/pluginhealth/scoring/model/updatecenter/SecurityWarning.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/SecurityWarningScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/SecurityWarningScoringTest.java
  war/src/main/resources/templates/scores/details.html
Labels: enhancement

#464 Add search, sort and pagination feature to probes table
  war/package.json
  war/src/main/js/index.js
  war/src/main/less/index.less
  war/src/main/resources/templates/probes/listing.html
  war/yarn.lock
Labels: enhancement
