Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2024-03, with the labels that each got.

#472 Uses newest scoring timestamp as etag header
  .gitignore
  Jenkinsfile_report
  fetch-report.sh
  war/src/main/java/io/jenkins/pluginhealth/scoring/http/ScoreAPI.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/http/ScoreAPITest.java
Labels: enhancement

#475 Plugin description migration probe
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/PluginDescriptionMigrationProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/DocumentationScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/PluginDescriptionMigrationProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/DocumentationScoringTest.java
Labels: enhancement

#478 Adds missing license header
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/JSR305Probe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/RenovateProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/IncrementalBuildDetectionProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/JSR305ProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/RenovateProbeTest.java
Labels: internal

#477 Setup spotless
  .editorconfig
  analytics/checkstyle-configuration.xml
  license-header/java.txt
  pom.xml
Labels: internal

#481 Explains where the plugins are learned from
  docs/ARCHITECTURE.adoc
Labels: documentation

#484 Disable spotless on tag
  Jenkinsfile
Labels: bug, internal

#486 Fixes adoptions scoring when last release is more recent than last commit
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/AdoptionScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/AdoptionScoringTest.java
Labels: bug

#488 The plugn description migration probe requires to have a clone of the code
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/PluginDescriptionMigrationProbe.java
Labels: bug

#492 Accepts all Renovate config file locations
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/AbstractDependencyBotConfigurationProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DependabotProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/RenovateProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DependabotProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/RenovateProbeTest.java
Labels: bug

#491 Provide scoring timestamp on JSON API
  war/src/main/java/io/jenkins/pluginhealth/scoring/http/ScoreAPI.java
  war/src/main/resources/application.yaml
  war/src/test/java/io/jenkins/pluginhealth/scoring/http/ScoreAPITest.java
Labels: enhancement

#494 Inheriting contributing guide should not lower score
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/DocumentationScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/ContributingGuidelinesProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/DocumentationScoringTest.java
Labels: enhancement

#496 fixup: pass OPTS as env var
  Jenkinsfile
Labels: chore
