Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2024-02, with the labels that each got.

#456 Update JVM requirement in contributing guide
  docs/CONTRIBUTING.adoc
Labels: documentation

#459 Resolves dependency bot probe result recognition
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoringTest.java
Labels: bug

#452 Provides link to help / guide how to improve scores
  core/src/main/java/io/jenkins/pluginhealth/scoring/model/Score.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/model/ScoringComponentResult.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/AdoptionScoring.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/DeprecatedPluginScoring.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoring.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/ScoringComponent.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoringTest.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/http/ScoreAPI.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/scores/ScoringEngine.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/scores/ScoringEngineTest.java
Labels: enhancement

#465 Improves pull request template so it's followed
  .github/pull_request_template.md
Labels: internal

#453 Add new probe to detect release-drafter usage
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DrafterReleaseProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DrafterReleaseProbeTest.java
Labels: enhancement

#466 Extracts plugin maintenance scoring into more precise scorings
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/DocumentationScoring.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/DocumentationScoringTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/PluginMaintenanceScoringTest.java
Labels: enhancement

#471 data: Updating CONTRIBUTING.adoc
  docs/CONTRIBUTING.adoc
Labels: documentation

#468 Using release drafter is not mandatory but a good documentation practice
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/ReleaseDrafterProbe.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/scores/DocumentationScoring.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/ReleaseDrafterProbeTest.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/scores/DocumentationScoringTest.java
Labels: enhancement
