Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2025-04, with the labels that each got.

#624 Method naming does not describe its purpose correctly
  core/src/main/java/io/jenkins/pluginhealth/scoring/repository/ScoreRepository.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/service/ScoreService.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/service/ScoreServiceIT.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/http/DataController.java
Labels: chore

#637 fixes Swarm plugin has no active security advisory #627
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/KnownSecurityVulnerabilityProbeTest.java
Labels: bug

#636 clarify a few items in the CONTRIBUTING guide
  docs/CONTRIBUTING.adoc
Labels: documentation

#635 Cannot compute score statistics when no scores are available
  core/src/main/java/io/jenkins/pluginhealth/scoring/service/ScoreService.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/service/ScoreServiceIT.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/service/ScoreServiceTest.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/http/DataController.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/http/ScoreAPI.java
  war/src/main/resources/templates/data/distribution.html
  war/src/test/java/io/jenkins/pluginhealth/scoring/http/ScoreAPITest.java
Labels: bug

#638 Stops using java.net.URL constructor
  war/src/main/java/io/jenkins/pluginhealth/scoring/service/PluginDocumentationService.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/service/UpdateCenterService.java
  war/src/test/java/io/jenkins/pluginhealth/scoring/service/PluginDocumentationServiceTest.java
Labels: chore

#644 Add `--repo` flag
  release.sh
Labels: chore

#645 Search plugins
  core/src/main/java/io/jenkins/pluginhealth/scoring/repository/PluginRepository.java
  core/src/main/java/io/jenkins/pluginhealth/scoring/service/PluginService.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/repository/PluginRepositoryIT.java
  war/pom.xml
  war/src/main/java/io/jenkins/pluginhealth/scoring/config/SecurityConfiguration.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/http/IndexController.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/schedule/DevProbeEngineScheduler.java
  war/src/main/java/io/jenkins/pluginhealth/scoring/schedule/DevUpdateCenterScheduler.java
  war/src/main/less/base/layout-commons.less
  war/src/main/resources/templates/index.html
  war/src/main/resources/templates/layouts/main.html
  war/src/main/svg/bar-chart.svg
  war/src/main/svg/probe.svg
  war/src/main/svg/search.svg
  war/src/test/java/io/jenkins/pluginhealth/scoring/http/IndexControllerTest.java
Labels: enhancement

#647 chore(Jenkinsfile): explicitly disable autoSemVer
  Jenkinsfile
Labels: chore
