Repository jenkins-infra/plugin-health-scoring, pull requests merged in 2025-01, with the labels that each got.

#583 Fixes invalid probe result in update center publication
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/UpdateCenterPluginPublicationProbeTest.java
Labels: bug

#584 Bump Spring-Boot BOM from 3.3.5 to 3.4.2
  pom.xml
Labels: dependencies

#422 Detects if the plugin repository main branch is built correctly
  core/src/main/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbe.java
  core/src/test/java/io/jenkins/pluginhealth/scoring/probes/DefaultBranchBuildStatusProbeTest.java
Labels: enhancement
